In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv("datasets/2020-05-21.csv")

/home/raghav/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/raghav/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/raghav/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/raghav/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/raghav/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]:
dataset.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0,SYMBOL,OPEN,HIGH,LOW,PREV.,CLOSE,LTP,CHNG,%CHNG,VOLUME\n(shares)\nVALUE\n(₹,Lakhs)\n52W,H,52W,L,TODAY
1,0,NIFTY,50,"9,079.45","9,178.55","9,056.10","9,066.55","9,098.00",31.45,0.35,"63,02,99,862","28,25,088.22","12,430.50","7,511.10",NaN,NaN
2,0,ITC,175.60,190.45,172.65,175.75,188.30,12.55,7.14,"5,82,49,413","1,07,359.49",310.00,134.60,NaN,NaN,NaN
3,0,HINDALCO,121.40,130.75,120.65,120.80,128.20,7.40,6.13,"3,42,53,897","43,601.79",221.20,84.90,NaN,NaN,NaN
4,0,ASIANPAINT,"1,503.00","1,583.50","1,501.00","1,500.05","1,576.50",76.45,5.10,"38,39,810","59,474.82","1,916.70","1,291.25",NaN,NaN,NaN

In [3]:
dataset

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0,SYMBOL,OPEN,HIGH,LOW,PREV.,CLOSE,LTP,CHNG,%CHNG,VOLUME\n(shares)\nVALUE\n(₹,Lakhs)\n52W,H,52W,L,TODAY
1,0,NIFTY,50,"9,079.45","9,178.55","9,056.10","9,066.55","9,098.00",31.45,0.35,"63,02,99,862","28,25,088.22","12,430.50","7,511.10",NaN,NaN
2,0,ITC,175.60,190.45,172.65,175.75,188.30,12.55,7.14,"5,82,49,413","1,07,359.49",310.00,134.60,NaN,NaN,NaN
3,0,HINDALCO,121.40,130.75,120.65,120.80,128.20,7.40,6.13,"3,42,53,897","43,601.79",221.20,84.90,NaN,NaN,NaN
4,0,ASIANPAINT,"1,503.00","1,583.50","1,501.00","1,500.05","1,576.50",76.45,5.10,"38,39,810","59,474.82","1,916.70","1,291.25",NaN,NaN,NaN
5,0,HEROMOTOCO,"2,043.00","2,130.00","2,020.00","2,023.60","2,105.35",81.75,4.04,"26,35,473","55,216.59","3,022.90","1,475.00",NaN,NaN,NaN
6,0,MARUTI,"4,890.00","5,073.80","4,851.05","4,891.95","5,045.00",153.05,3.13,"18,65,941","93,443.90","7,758.70","4,001.10",NaN,NaN,NaN
7,0,UPL,359.65,370.00,356.35,356.55,367.30,10.75,3.02,"1,00,66,968","36,568.26",709.05,240.15,NaN,NaN,NaN
8,0,SUNPHARMA,455.50,469.00,453.00,455.75,467.90,12.15,2.67,"89,52,620","41,331.56",504.80,312.00,NaN,NaN,NaN
9,0,EICHERMOT,"13,477.00","14,199.00","13,356.10","13,675.10","14,034.90",359.80,2.63,"3,21,785","44,947.54","23,450.00","12,450.10",NaN,NaN,NaN
10,0,BAJAJ-AUTO,"2,634.50","2,724.20","2,621.25","2,557.75","2,625.00",67.25,2.63,"34,76,278","92,584.75","3,315.15","1,788.65",NaN,NaN,NaN
11,0,WIPRO,183.40,191.70,183.40,184.95,189.05,4.10,2.22,"71,14,838","13,424.99",301.60,159.40,NaN,NaN,NaN
12,0,GAIL,86.40,88.20,85.50,86.25,88.10,1.85,2.14,"1,28,50,018","11,206.50",182.70,65.00,NaN,NaN,NaN
13,0,INFRATEL,204.00,209.65,204.00,200.85,205.15,4.30,2.14,"1,34,38,332","27,803.91",296.50,120.05,NaN,NaN,NaN
14,0,VEDL,89.00,91.75,88.15,88.55,90.15,1.60,1.81,"3,14,62,300","28,297.19",180.00,60.20,NaN,NaN,NaN
15,0,TCS,"1,946.00","1,998.00","1,941.15","1,953.60","1,988.00",34.40,1.76,"33,95,470","67,149.15","2,296.20","1,506.05",NaN,NaN,NaN
16,0,COALINDIA,123.90,126.25,122.80,123.25,125.10\n1.85,1.50,"61,79,114","7,703.50",271.45,119.20,NaN,NaN,NaN,NaN
17,0,HCLTECH,529.80,537.50,523.40,526.75,534.60,7.85,1.49,"45,13,328","23,967.58",623.50,375.25,NaN,NaN,NaN
18,0,BPCL,310.00,316.00,301.60,308.90,312.50,3.60,1.17,"74,54,665","23,113.19",549.00,252.00,NaN,NaN,NaN
19,0,ULTRACEMCO,"3,588.00","3,590.00","3,496.35","3,528.50","3,562.30",33.80,0.96,"7,09,757","25,170.33","4,904.95","2,910.00",NaN,NaN,NaN
20,0,TATAMOTORS,83.10,85.20,82.90,83.45,83.95,0.50,0.60,"3,72,17,540","31,359.50",201.70,63.50,NaN,NaN,NaN
21,0,M&M,400.15,412.20,397.80,405.05,407.00,1.95,0.48,"62,36,521","25,354.58",683.00,245.40,NaN,NaN,NaN
22,0,INFY,666.50,679.45,665.40,669.55,672.70,3.15,0.47,"71,82,132","48,289.78",847.00,509.25,NaN,NaN,NaN
23,0,RELIANCE,"1,435.00","1,461.45","1,425.00","1,433.70","1,439.65",5.95,0.42,"1,80,48,515","2,60,609.73","1,601.53",866.98,NaN,NaN,NaN
24,0,HDFCBANK,861.45,884.00,852.30,857.10,860.00,2.90,0.34,"2,42,18,091","2,10,854.81","1,305.50",738.75,NaN,NaN,NaN
25,0,IOC,74.10,74.95,73.00,74.10,74.35\n0.25,0.34,"1,02,08,463","7,570.60",170.75,71.15,NaN,NaN,NaN,NaN
26,0,TECHM,519.95,521.50,510.05,519.20,520.25,1.05,0.20,"25,38,318","13,119.04",845.90,471.40,NaN,NaN,NaN
27,0,TATASTEEL,283.90,286.25,278.50,283.20,283.50,0.30,0.11,"1,29,68,906","36,672.18",518.60,250.85,NaN,NaN,NaN
28,0,ZEEL,155.10,159.50,152.85,153.55,153.70,0.15,0.10,"1,54,73,597","24,239.39",405.20,114.00,NaN,NaN,NaN
29,0,BHARTIARTL,590.50,604.50,585.40,594.05,594.50\n0.45,0.08,"2,02,68,828","1,20,638.04",612.00,321.15,NaN,NaN,NaN,NaN
30,0,TITAN,854.00,860.00,843.90,848.70,849.00,0.30,0.04,"22,12,399","18,793.44","1,389.95",720.90,NaN,NaN,NaN
31,0,POWERGRID,157.55,159.85,157.00,158.45,158.50,0.05,0.03,"96,56,979","15,265.75",216.25,122.15,NaN,NaN,NaN
32,0,NESTLEIND,"16,330.00","16,505.00","16,265.00","16,303.40","16,297.00",-6.40,-0.04,"1,20,822","19,773.28","18,369.95","10,493.95",NaN,NaN,NaN
33,0,ICICIBANK,306.00,312.80,302.00,305.65,304.30,-1.35,-0.44,"4,30,04,257","1,32,427.31",552.20,268.30,NaN,NaN,NaN
34,0,CIPLA,620.65,626.85,612.30,620.65,616.80\n-3.85,-0.62,"79,08,843","48,969.18",632.65,355.30,NaN,NaN,NaN,NaN
35,0,BRITANNIA,"3,120.10","3,157.00","3,099.00","3,127.85","3,107.60",-20.25,-0.65,"5,73,550","17,912.14","3,583.75","2,100.00",NaN,NaN,NaN
36,0,KOTAKBANK,"1,165.00","1,189.55","1,144.60","1,160.10","1,151.35",-8.75,-0.75,"59,70,190","69,899.58","1,740.00","1,001.00",NaN,NaN,NaN
37,0,JSWSTEEL,172.00,174.85,168.95,171.05,169.50,-1.55,-0.91,"1,10,43,677","18,971.93",297.50,132.50,NaN,NaN,NaN
38,0,SBIN,153.65,156.15,151.50,153.40,151.95\n-1.45,-0.95,"6,09,78,234","93,918.68",373.80,151.15,NaN,NaN,NaN,NaN
39,0,HINDUNILVR,"1,999.00","2,003.40","1,955.20","1,990.85","1,970.80",-20.05,-1.01,"42,53,431","84,165.19","2,614.30","1,659.05",NaN,NaN,NaN
40,0,SHREECEM,"19,156.00","19,349.60","18,750.00","19,411.65","19,155.00",-256.65,-1.32,"83,207","15,873.15","25,355.00","15,410.00",NaN,NaN,NaN
41,0,ONGC,78.75,79.00,76.40,78.00,76.95,-1.05,-1.35,"1,79,70,234","13,865.83",178.90,50.00,NaN,NaN,NaN
42,0,AXISBANK,363.00,369.00,355.70,362.50,357.10,-5.40,-1.49,"2,47,66,949","89,896.59",827.75,286.00,NaN,NaN,NaN
43,0,LT,835.95,845.00,818.10,835.00,821.15,-13.85,-1.66,"46,91,524","38,725.72","1,607.00",661.00,NaN,NaN,NaN
44,0,DRREDDY,"3,950.00","3,954.15","3,825.50","3,910.20","3,838.05",-72.15,-1.85,"17,30,890","67,020.06","4,132.20","2,351.20",NaN,NaN,NaN
45,0,GRASIM,536.85,536.95,521.55,536.85,526.00,-10.85,-2.02,"19,95,077","10,522.24",959.80,385.05,NaN,NaN,NaN
46,0,ADANIPORTS,319.40,322.15,315.40,323.75,317.00,-6.75,-2.08,"45,92,374","14,612.02",430.60,203.00,NaN,NaN,NaN
47,0,HDFC,"1,632.90","1,651.80","1,590.00","1,627.00","1,592.05",-34.95,-2.15,"70,24,676","1,14,005.57","2,499.90","1,473.45",NaN,NaN,NaN
48,0,INDUSINDBK,362.30,364.00,343.20,357.30,347.20,-10.10,-2.83,"2,55,01,164","90,427.13","1,672.95",235.55,NaN,NaN,NaN
49,0,BAJFINANCE,"2,059.00","2,077.55","1,974.50","2,042.80","1,984.00\n-58.80",-2.88,"98,63,774","2,00,150.77","4,923.40","1,915.65",NaN,NaN,NaN,NaN
50,0,NTPC,92.15,92.65,89.80,92.90,90.20,-2.70,-2.91,"2,01,26,229","18,268.58",145.85,73.20,NaN,NaN,NaN
51,0,BAJAJFINSV,"4,725.00","4,742.70","4,515.00","4,702.05","4,530.00",-172.05,-3.66,"10,90,464","50,551.40","9,950.00","4,160.25",NaN,NaN,NaN

In [6]:
columns_null = [col for col in dataset.columns if dataset[col].isna().any()]

In [7]:
columns_null

['11', '12', '13', '14']